[package]
name = "contain-test-installer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "contain-test-installer"
path = "src/main.rs"

[[bin]]
name = "contain-registry-noise"
path = "src/registry_noise.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
winreg.workspace = true
serde_json.workspace = true
windows-sys.workspace = true
