"""Keep all original stress scores/counters; publish only the controlled fixture data."""
import importlib.util
import json
import sys
from pathlib import Path

spec=importlib.util.spec_from_file_location("archive",Path(__file__).with_name("hotpath-artifact.py"))
archive=importlib.util.module_from_spec(spec)
spec.loader.exec_module(archive)
root=Path(sys.argv[1])
output=Path(sys.argv[2])
for run in root.glob("run-*"):
    if not run.is_dir():
        continue
    dest=output/run.name
    dest.mkdir(parents=True,exist_ok=True)
    for name in ("comparison.json", "environment.json"):
        if (run/name).exists():
            dest.joinpath(name).write_bytes((run/name).read_bytes())
    for measurement in run.glob("*/measurement.json"):
        record=json.loads(measurement.read_text(encoding="utf-8-sig"))
        trial=dest/measurement.parent.name
        exported=archive.write_trial(measurement.parent,trial,record["mode"],record.get("harness_error", ""))
        # Original stress gate has its own fixed 2500 / 25000 denominator and thresholds.
        # The small-fixture gate generated by the common archive helper is not applicable.
        record["artifact_export"]={key:exported[key] for key in ("missing_capture", "incomplete_scoring", "scoring_read_error") if key in exported}
        trial.joinpath("result.json").write_text(json.dumps(record,indent=2),encoding="utf-8")
