"""Keep all original stress scores/counters; publish only the controlled fixture data."""
import importlib.util
import json
import sys
from pathlib import Path

spec=importlib.util.spec_from_file_location("archive",Path(__file__).with_name("hotpath-artifact.py"))
archive=importlib.util.module_from_spec(spec)
spec.loader.exec_module(archive)
root=Path(sys.argv[1])
output=Path(sys.argv[2])
for comparison in root.glob("run-*/comparison.json"):
    dest=output/comparison.parent.name
    dest.mkdir(parents=True,exist_ok=True)
    dest.joinpath("comparison.json").write_bytes(comparison.read_bytes())
    dest.joinpath("environment.json").write_bytes(comparison.with_name("environment.json").read_bytes())
    for measurement in comparison.parent.glob("*/measurement.json"):
        record=json.loads(measurement.read_text(encoding="utf-8-sig"))
        trial=dest/measurement.parent.name
        archive.write_trial(measurement.parent,trial,record["mode"],"")
        # Original stress gate has its own fixed 2500 / 25000 denominator and thresholds.
        # The small-fixture gate generated by the common archive helper is not applicable.
        trial.joinpath("result.json").write_bytes(measurement.read_bytes())
